services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/samHoefnagels/metabase-pace-webapp.git # optional
    plan: starter # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: elephant
          property: connectionString
      port: 3000
databases:
  - name: elephant
    databaseName: metabasedb
    ipAllowList: [] # only allow internal connections
